import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  darkMode: ['class'],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        'light-1': '#ffffff',
        'light-2': '#ffffff',
        'light-3': 'rgba(0, 0, 0, 0.6)',
        'light-4': 'rgba(0, 0, 0, 0.8)',
        'light-5': '#ffffff',
        'dark-1': '#000000',
        'dark-2': '#000000',
        'dark-3': '#000000',
        'dark-4': '#000000',
        'primary-500': '#10b981',
        'secondary-500': '#64748b',
        'glassmorphism': 'rgba(255, 255, 255, 0.15)',
        'glassmorphism-dark': 'rgba(255, 255, 255, 0.05)',
        'glass-border': 'rgba(255, 255, 255, 0.2)',
        'glass-border-dark': 'rgba(255, 255, 255, 0.1)',
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "#10b981",
          50: "#ecfdf5",
          100: "#d1fae5",
          200: "#a7f3d0",
          300: "#6ee7b7",
          400: "#34d399",
          500: "#10b981",
          600: "#059669",
          700: "#047857",
          800: "#065f46",
          900: "#064e3b",
          950: "#022c22",
        },
        slate: {
          50: "#f8fafc",
          100: "#f1f5f9",
          200: "#e2e8f0",
          300: "#cbd5e1",
          400: "#94a3b8",
          500: "#64748b",
          600: "#475569",
          700: "#334155",
          800: "#1e293b",
          900: "#0f172a",
          950: "#020617",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      backdropBlur: {
        'xs': '2px',
        'sm': '4px',
        'md': '8px',
        'lg': '16px',
        'xl': '24px',
        '2xl': '40px',
        '3xl': '64px',
      },
      fontSize: {
        'heading1-bold': ['36px', { lineHeight: '140%', fontWeight: '700' }],
        'heading2-bold': ['30px', { lineHeight: '140%', fontWeight: '700' }],
        'heading3-bold': ['24px', { lineHeight: '140%', fontWeight: '700' }],
        'heading4-medium': ['20px', { lineHeight: '140%', fontWeight: '500' }],
        'body-bold': ['18px', { lineHeight: '140%', fontWeight: '700' }],
        'body-semibold': ['18px', { lineHeight: '140%', fontWeight: '600' }],
        'body-medium': ['18px', { lineHeight: '140%', fontWeight: '500' }],
        'body-normal': ['18px', { lineHeight: '140%', fontWeight: '400' }],
        'base-regular': ['16px', { lineHeight: '140%', fontWeight: '400' }],
        'base-medium': ['16px', { lineHeight: '140%', fontWeight: '500' }],
        'base-semibold': ['16px', { lineHeight: '140%', fontWeight: '600' }],
        'small-regular': ['14px', { lineHeight: '140%', fontWeight: '400' }],
        'small-medium': ['14px', { lineHeight: '140%', fontWeight: '500' }],
        'small-semibold': ['14px', { lineHeight: '140%', fontWeight: '600' }],
        'subtle-medium': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'tiny-medium': ['10px', { lineHeight: '140%', fontWeight: '500' }],
      },
      screens: {
        'xs': '400px',
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}

export default config
